# Generated by Django 2.2 on 2019-08-15 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumo',
            name='cantidad_total_en_gramos',
            field=models.FloatField(blank=True, null=True, verbose_name='Cantidad Total en Gramos'),
        ),
        migrations.AddField(
            model_name='insumo',
            name='codigo',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Código'),
        ),
        migrations.AddField(
            model_name='insumo',
            name='costo_total_al_gramo',
            field=models.FloatField(blank=True, null=True, verbose_name='Costo Total al Gramos'),
        ),
        migrations.AddField(
            model_name='insumo',
            name='descripcion',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='insumo',
            name='stock_minimo',
            field=models.FloatField(blank=True, null=True, verbose_name='Stock Mínimo'),
        ),
    ]
