package view;

import javax.swing.ImageIcon;

/**
 *
 * @author Daniel Castillo Villamarín
 */
public class ViewLogin extends javax.swing.JFrame {

    private boolean password;
    int x,y;
    
    public ViewLogin() {
        initComponents();
        password=true;
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbClose = new javax.swing.JButton();
        jtUsername = new javax.swing.JTextField();
        jPasswordField = new javax.swing.JPasswordField();
        jlSeparatorPassword = new javax.swing.JLabel();
        jlSeparatorUsername = new javax.swing.JLabel();
        jbGo = new javax.swing.JButton();
        jlFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close.png"))); // NOI18N
        jbClose.setBorder(null);
        jbClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jbCloseMouseReleased(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbCloseMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbCloseMouseEntered(evt);
            }
        });
        getContentPane().add(jbClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, -1, -1));

        jtUsername.setFont(new java.awt.Font("Arima Madurai", 0, 24)); // NOI18N
        jtUsername.setForeground(new java.awt.Color(153, 153, 153));
        jtUsername.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtUsername.setText("Username");
        jtUsername.setBorder(null);
        jtUsername.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtUsernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtUsernameFocusLost(evt);
            }
        });
        getContentPane().add(jtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 170, 30));

        jPasswordField.setFont(new java.awt.Font("Arima Madurai", 0, 24)); // NOI18N
        jPasswordField.setForeground(new java.awt.Color(153, 153, 153));
        jPasswordField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPasswordField.setText("Password");
        jPasswordField.setBorder(null);
        jPasswordField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordFieldFocusGained(evt);
            }
        });
        getContentPane().add(jPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 170, 20));

        jlSeparatorPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/separator.png"))); // NOI18N
        getContentPane().add(jlSeparatorPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, -1, -1));

        jlSeparatorUsername.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/separator.png"))); // NOI18N
        getContentPane().add(jlSeparatorUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, -1, -1));

        jbGo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Go!.png"))); // NOI18N
        jbGo.setBorder(null);
        jbGo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jbGo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 310, -1, -1));

        jlFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/FondoLogin.png"))); // NOI18N
        jlFondo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jlFondoMouseDragged(evt);
            }
        });
        jlFondo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jlFondoMousePressed(evt);
            }
        });
        getContentPane().add(jlFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbCloseMouseEntered
        jbClose.setIcon(new ImageIcon(getClass().getResource("/icons/closeEntered.png")));
    }//GEN-LAST:event_jbCloseMouseEntered

    private void jbCloseMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbCloseMouseReleased
        jbClose.setIcon(new ImageIcon(getClass().getResource("/icons/close.png")));
    }//GEN-LAST:event_jbCloseMouseReleased

    private void jbCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbCloseMouseExited
        jbClose.setIcon(new ImageIcon(getClass().getResource("/icons/close.png")));
    }//GEN-LAST:event_jbCloseMouseExited

    private void jtUsernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtUsernameFocusGained
        if(jtUsername.getText().equals("Username"))
        {
            jtUsername.setText("");
        }
    }//GEN-LAST:event_jtUsernameFocusGained

    private void jtUsernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtUsernameFocusLost
        if(jtUsername.getText().equals(""))
        {
            jtUsername.setText("Username");
        }
    }//GEN-LAST:event_jtUsernameFocusLost

    private void jPasswordFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordFieldFocusGained
        if(password=true)
        {
            jPasswordField.setText("");
            password=false;
        }
    }//GEN-LAST:event_jPasswordFieldFocusGained

    private void jlFondoMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlFondoMouseDragged
        this.setLocation(this.getLocation().x + evt.getX() - x, this.getLocation().y + evt.getY() - y);
    }//GEN-LAST:event_jlFondoMouseDragged

    private void jlFondoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlFondoMousePressed
        x=evt.getX();
        y=evt.getY();
    }//GEN-LAST:event_jlFondoMousePressed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField jPasswordField;
    public javax.swing.JButton jbClose;
    public javax.swing.JButton jbGo;
    private javax.swing.JLabel jlFondo;
    private javax.swing.JLabel jlSeparatorPassword;
    private javax.swing.JLabel jlSeparatorUsername;
    private javax.swing.JTextField jtUsername;
    // End of variables declaration//GEN-END:variables
}
