/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.ImageIcon;

/**
 *
 * @author Magneto
 */
public class ViewDashboard extends javax.swing.JFrame {

    int x,y;
    
    public ViewDashboard() {
        initComponents();
        this.setLocationRelativeTo(null);
        //this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpFondo = new javax.swing.JPanel();
        jpBanner = new javax.swing.JPanel();
        jbClose = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jlBanner = new javax.swing.JLabel();
        jpMenu = new javax.swing.JPanel();
        jpEncabezado = new javax.swing.JPanel();
        jlEncabezado = new javax.swing.JLabel();
        jpGProductos = new javax.swing.JPanel();
        jlGProductos = new javax.swing.JLabel();
        iconProductos = new javax.swing.JLabel();
        jpGProveedores = new javax.swing.JPanel();
        jlGProveedores = new javax.swing.JLabel();
        iconProveedores = new javax.swing.JLabel();
        jpGUsuarios = new javax.swing.JPanel();
        jlGUsuarios = new javax.swing.JLabel();
        iconUsuarios = new javax.swing.JLabel();
        jpGClientes = new javax.swing.JPanel();
        jlGClientes = new javax.swing.JLabel();
        iconClientes = new javax.swing.JLabel();
        jpGReportes = new javax.swing.JPanel();
        jlGReportes = new javax.swing.JLabel();
        iconReportes = new javax.swing.JLabel();
        jpGFacturas = new javax.swing.JPanel();
        jlGFacturas = new javax.swing.JLabel();
        iconFacturas = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);

        jpFondo.setBackground(new java.awt.Color(255, 255, 255));
        jpFondo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255), 2));
        jpFondo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jpFondoMouseDragged(evt);
            }
        });
        jpFondo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jpFondoMousePressed(evt);
            }
        });

        jpBanner.setBackground(new java.awt.Color(145, 228, 251));

        jbClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/closeDash.png"))); // NOI18N
        jbClose.setBorder(null);
        jbClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbCloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbCloseMouseExited(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(145, 228, 251));

        jlBanner.setFont(new java.awt.Font("Arima Madurai", 0, 27)); // NOI18N
        jlBanner.setForeground(new java.awt.Color(102, 102, 102));
        jlBanner.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlBanner.setText("AGUA Y HARINA");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlBanner, javax.swing.GroupLayout.DEFAULT_SIZE, 501, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jlBanner, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jpBannerLayout = new javax.swing.GroupLayout(jpBanner);
        jpBanner.setLayout(jpBannerLayout);
        jpBannerLayout.setHorizontalGroup(
            jpBannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpBannerLayout.createSequentialGroup()
                .addContainerGap(119, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(116, 116, 116)
                .addComponent(jbClose, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jpBannerLayout.setVerticalGroup(
            jpBannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpBannerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbClose, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jpMenu.setBackground(new java.awt.Color(153, 255, 255));

        jpEncabezado.setBackground(new java.awt.Color(153, 255, 255));

        jlEncabezado.setFont(new java.awt.Font("Arima Madurai", 1, 18)); // NOI18N
        jlEncabezado.setForeground(new java.awt.Color(102, 102, 102));
        jlEncabezado.setText("PIZZA INVENTION");

        javax.swing.GroupLayout jpEncabezadoLayout = new javax.swing.GroupLayout(jpEncabezado);
        jpEncabezado.setLayout(jpEncabezadoLayout);
        jpEncabezadoLayout.setHorizontalGroup(
            jpEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpEncabezadoLayout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(jlEncabezado)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpEncabezadoLayout.setVerticalGroup(
            jpEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpEncabezadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlEncabezado)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jpGProductos.setBackground(new java.awt.Color(153, 255, 255));
        jpGProductos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jpGProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpGProductosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jpGProductosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpGProductosMouseExited(evt);
            }
        });

        jlGProductos.setFont(new java.awt.Font("Arima Madurai", 0, 18)); // NOI18N
        jlGProductos.setText("Gestión de Productos");

        javax.swing.GroupLayout jpGProductosLayout = new javax.swing.GroupLayout(jpGProductos);
        jpGProductos.setLayout(jpGProductosLayout);
        jpGProductosLayout.setHorizontalGroup(
            jpGProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpGProductosLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jlGProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(iconProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jpGProductosLayout.setVerticalGroup(
            jpGProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpGProductosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpGProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(iconProductos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlGProductos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jpGProveedores.setBackground(new java.awt.Color(153, 255, 255));
        jpGProveedores.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jpGProveedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpGProveedoresMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jpGProveedoresMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpGProveedoresMouseExited(evt);
            }
        });

        jlGProveedores.setFont(new java.awt.Font("Arima Madurai", 0, 18)); // NOI18N
        jlGProveedores.setText("Gestión de Proveedores");

        javax.swing.GroupLayout jpGProveedoresLayout = new javax.swing.GroupLayout(jpGProveedores);
        jpGProveedores.setLayout(jpGProveedoresLayout);
        jpGProveedoresLayout.setHorizontalGroup(
            jpGProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpGProveedoresLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlGProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(iconProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jpGProveedoresLayout.setVerticalGroup(
            jpGProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpGProveedoresLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpGProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(iconProveedores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlGProveedores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jpGUsuarios.setBackground(new java.awt.Color(153, 255, 255));
        jpGUsuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jpGUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpGUsuariosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jpGUsuariosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpGUsuariosMouseExited(evt);
            }
        });

        jlGUsuarios.setFont(new java.awt.Font("Arima Madurai", 0, 18)); // NOI18N
        jlGUsuarios.setText("Gestión de Usuarios");

        javax.swing.GroupLayout jpGUsuariosLayout = new javax.swing.GroupLayout(jpGUsuarios);
        jpGUsuarios.setLayout(jpGUsuariosLayout);
        jpGUsuariosLayout.setHorizontalGroup(
            jpGUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpGUsuariosLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jlGUsuarios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(iconUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jpGUsuariosLayout.setVerticalGroup(
            jpGUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpGUsuariosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpGUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlGUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(iconUsuarios, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jpGClientes.setBackground(new java.awt.Color(153, 255, 255));
        jpGClientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jpGClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpGClientesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jpGClientesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpGClientesMouseExited(evt);
            }
        });

        jlGClientes.setFont(new java.awt.Font("Arima Madurai", 0, 18)); // NOI18N
        jlGClientes.setText("Gestión de Clientes");

        javax.swing.GroupLayout jpGClientesLayout = new javax.swing.GroupLayout(jpGClientes);
        jpGClientes.setLayout(jpGClientesLayout);
        jpGClientesLayout.setHorizontalGroup(
            jpGClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpGClientesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlGClientes)
                .addGap(64, 64, 64)
                .addComponent(iconClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jpGClientesLayout.setVerticalGroup(
            jpGClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpGClientesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpGClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlGClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jpGClientesLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(iconClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jpGReportes.setBackground(new java.awt.Color(153, 255, 255));
        jpGReportes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jpGReportes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpGReportesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jpGReportesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpGReportesMouseExited(evt);
            }
        });

        jlGReportes.setFont(new java.awt.Font("Arima Madurai", 0, 18)); // NOI18N
        jlGReportes.setText("Gestión de Reportes");

        javax.swing.GroupLayout jpGReportesLayout = new javax.swing.GroupLayout(jpGReportes);
        jpGReportes.setLayout(jpGReportesLayout);
        jpGReportesLayout.setHorizontalGroup(
            jpGReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpGReportesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlGReportes)
                .addGap(57, 57, 57)
                .addComponent(iconReportes, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jpGReportesLayout.setVerticalGroup(
            jpGReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpGReportesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpGReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlGReportes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jpGReportesLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(iconReportes, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jpGFacturas.setBackground(new java.awt.Color(153, 255, 255));
        jpGFacturas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jpGFacturas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpGFacturasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jpGFacturasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpGFacturasMouseExited(evt);
            }
        });

        jlGFacturas.setFont(new java.awt.Font("Arima Madurai", 0, 18)); // NOI18N
        jlGFacturas.setText("Gestión de Facturas");

        javax.swing.GroupLayout jpGFacturasLayout = new javax.swing.GroupLayout(jpGFacturas);
        jpGFacturas.setLayout(jpGFacturasLayout);
        jpGFacturasLayout.setHorizontalGroup(
            jpGFacturasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpGFacturasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlGFacturas)
                .addGap(58, 58, 58)
                .addComponent(iconFacturas, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jpGFacturasLayout.setVerticalGroup(
            jpGFacturasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpGFacturasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpGFacturasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlGFacturas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jpGFacturasLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(iconFacturas, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout jpMenuLayout = new javax.swing.GroupLayout(jpMenu);
        jpMenu.setLayout(jpMenuLayout);
        jpMenuLayout.setHorizontalGroup(
            jpMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpEncabezado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jpMenuLayout.createSequentialGroup()
                .addGroup(jpMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jpGFacturas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpGReportes, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpGClientes, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpGUsuarios, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpGProveedores, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpGProductos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 1, Short.MAX_VALUE))
        );
        jpMenuLayout.setVerticalGroup(
            jpMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMenuLayout.createSequentialGroup()
                .addComponent(jpEncabezado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpGProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpGProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpGUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpGClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpGReportes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpGFacturas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 490, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jpFondoLayout = new javax.swing.GroupLayout(jpFondo);
        jpFondo.setLayout(jpFondoLayout);
        jpFondoLayout.setHorizontalGroup(
            jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpFondoLayout.createSequentialGroup()
                .addComponent(jpMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpBanner, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jpFondoLayout.setVerticalGroup(
            jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jpMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jpFondoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jpBanner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jpFondoMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpFondoMouseDragged
        this.setLocation(this.getLocation().x + evt.getX() - x, this.getLocation().y + evt.getY() - y);
    }//GEN-LAST:event_jpFondoMouseDragged

    private void jpFondoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpFondoMousePressed
        x=evt.getX();
        y=evt.getY();
    }//GEN-LAST:event_jpFondoMousePressed

    private void jbCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbCloseMouseEntered
        try
        {
            jbClose.setIcon(new ImageIcon(getClass().getResource("/images/closeEnteredDash.png")));
        }
        catch(NullPointerException exception)
        {
            System.out.println("ViewDashboard: jbCloseMouseEntered: NullPointerException: "+exception.getMessage());
        }
    }//GEN-LAST:event_jbCloseMouseEntered

    private void jbCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbCloseMouseExited
        try
        {
            jbClose.setIcon(new ImageIcon(getClass().getResource("/images/closeDash.png")));
        }
        catch(NullPointerException exception)
        {
            System.out.println("ViewLogin: jbCloseMouseExited: NullPointerException: "+exception.getMessage());
        }
    }//GEN-LAST:event_jbCloseMouseExited

    private void jpGProductosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpGProductosMouseEntered
        this.jpGProductos.setBackground(jpBanner.getBackground());
        this.iconProductos.setIcon(new ImageIcon(getClass().getResource("/images/flecha.png")));
    }//GEN-LAST:event_jpGProductosMouseEntered

    private void jpGProductosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpGProductosMouseExited
        this.jpGProductos.setBackground(jpEncabezado.getBackground());
        this.iconProductos.setIcon(new ImageIcon());
    }//GEN-LAST:event_jpGProductosMouseExited

    private void jpGProveedoresMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpGProveedoresMouseEntered
        this.jpGProveedores.setBackground(jpBanner.getBackground());
        this.iconProveedores.setIcon(new ImageIcon(getClass().getResource("/images/flecha.png")));
    }//GEN-LAST:event_jpGProveedoresMouseEntered

    private void jpGProveedoresMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpGProveedoresMouseExited
        this.jpGProveedores.setBackground(jpEncabezado.getBackground());
        this.iconProveedores.setIcon(new ImageIcon());
    }//GEN-LAST:event_jpGProveedoresMouseExited

    private void jpGUsuariosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpGUsuariosMouseEntered
        this.jpGUsuarios.setBackground(jpBanner.getBackground());
        this.iconUsuarios.setIcon(new ImageIcon(getClass().getResource("/images/flecha.png")));
    }//GEN-LAST:event_jpGUsuariosMouseEntered

    private void jpGUsuariosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpGUsuariosMouseExited
        this.jpGUsuarios.setBackground(jpEncabezado.getBackground());
        this.iconUsuarios.setIcon(new ImageIcon());
    }//GEN-LAST:event_jpGUsuariosMouseExited

    private void jpGClientesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpGClientesMouseEntered
        this.jpGClientes.setBackground(jpBanner.getBackground());
        this.iconClientes.setIcon(new ImageIcon(getClass().getResource("/images/flecha.png")));
    }//GEN-LAST:event_jpGClientesMouseEntered

    private void jpGClientesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpGClientesMouseExited
        this.jpGClientes.setBackground(jpEncabezado.getBackground());
        this.iconClientes.setIcon(new ImageIcon());
    }//GEN-LAST:event_jpGClientesMouseExited

    private void jpGReportesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpGReportesMouseEntered
        this.jpGReportes.setBackground(jpBanner.getBackground());
        this.iconReportes.setIcon(new ImageIcon(getClass().getResource("/images/flecha.png")));
    }//GEN-LAST:event_jpGReportesMouseEntered

    private void jpGReportesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpGReportesMouseExited
        this.jpGReportes.setBackground(jpEncabezado.getBackground());
        this.iconReportes.setIcon(new ImageIcon());
    }//GEN-LAST:event_jpGReportesMouseExited

    private void jpGFacturasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpGFacturasMouseEntered
       this.jpGFacturas.setBackground(jpBanner.getBackground());
       this.iconFacturas.setIcon(new ImageIcon(getClass().getResource("/images/flecha.png")));
    }//GEN-LAST:event_jpGFacturasMouseEntered

    private void jpGFacturasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpGFacturasMouseExited
        this.jpGFacturas.setBackground(jpEncabezado.getBackground());
        this.iconFacturas.setIcon(new ImageIcon());
    }//GEN-LAST:event_jpGFacturasMouseExited

    private void jpGProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpGProductosMouseClicked
        this.jlBanner.setText("Gestión de Productos");
    }//GEN-LAST:event_jpGProductosMouseClicked

    private void jpGProveedoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpGProveedoresMouseClicked
        this.jlBanner.setText("Gestión de Proveedores");
    }//GEN-LAST:event_jpGProveedoresMouseClicked

    private void jpGUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpGUsuariosMouseClicked
        this.jlBanner.setText("Gestión de Usuarios");
    }//GEN-LAST:event_jpGUsuariosMouseClicked

    private void jpGClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpGClientesMouseClicked
        this.jlBanner.setText("Gestión de Clientes");
    }//GEN-LAST:event_jpGClientesMouseClicked

    private void jpGReportesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpGReportesMouseClicked
        this.jlBanner.setText("Gestión de Reportes");
    }//GEN-LAST:event_jpGReportesMouseClicked

    private void jpGFacturasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpGFacturasMouseClicked
        this.jlBanner.setText("Gestión de Facturas");
    }//GEN-LAST:event_jpGFacturasMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel iconClientes;
    private javax.swing.JLabel iconFacturas;
    private javax.swing.JLabel iconProductos;
    private javax.swing.JLabel iconProveedores;
    private javax.swing.JLabel iconReportes;
    private javax.swing.JLabel iconUsuarios;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JButton jbClose;
    private javax.swing.JLabel jlBanner;
    private javax.swing.JLabel jlEncabezado;
    private javax.swing.JLabel jlGClientes;
    private javax.swing.JLabel jlGFacturas;
    private javax.swing.JLabel jlGProductos;
    private javax.swing.JLabel jlGProveedores;
    private javax.swing.JLabel jlGReportes;
    private javax.swing.JLabel jlGUsuarios;
    private javax.swing.JPanel jpBanner;
    private javax.swing.JPanel jpEncabezado;
    private javax.swing.JPanel jpFondo;
    private javax.swing.JPanel jpGClientes;
    private javax.swing.JPanel jpGFacturas;
    private javax.swing.JPanel jpGProductos;
    private javax.swing.JPanel jpGProveedores;
    private javax.swing.JPanel jpGReportes;
    private javax.swing.JPanel jpGUsuarios;
    private javax.swing.JPanel jpMenu;
    // End of variables declaration//GEN-END:variables
}
