# Generated by Django 2.2 on 2019-08-16 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proveedor',
            old_name='nombres',
            new_name='nombre',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='apellidos',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='fecha_nacimiento',
        ),
        migrations.AddField(
            model_name='proveedor',
            name='direccion',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono'),
        ),
    ]
