# Generated by Django 2.2 on 2019-08-29 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0002_auto_20190816_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='tipo_documento',
            field=models.CharField(blank=True, choices=[('CC', 'CC'), ('TI', 'TI'), ('NIT', 'NIT'), ('PASAPORTE', 'PASAPORTE')], max_length=20, null=True, verbose_name='Tipo de Documento'),
        ),
    ]
